### ISSUE TITLE
installing this on webserver

### ISSUE THREAD

**Issue by j86schroeder** [gera2ld/markmap-vscode#14]
How do I go about installing this on my hosted web server?

**Comment by gera2ld** [comment]
What do you mean by web server? This is a VSCode extension and should work in any environment with VSCode extension APIs properly implemented.

**Comment by j86schroeder** [comment]
Well I got it on my hosted web server, but I updated the .html file but it doesn't reflect my changes... strange.

https://mybibletopics.com/markmap

**Comment by gera2ld** [comment]
Can confirm it works at github.dev , please feel free to provide more info and reopen this issue if it persists.
