### ISSUE TITLE
Publish extension to open-vsx

### ISSUE THREAD

**Issue by Tchoupinax** [gera2ld/markmap-vscode#2]
Hello :)

I'm using [VSCodium](https://github.com/VSCodium/vscodium) and I will be happy if you could publish your extension on https://open-vsx.org/.

The guide to publish is readable [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

Thank you for your work!

**Comment by gera2ld** [comment]
It's published at <https://open-vsx.org/extension/gera2ld/markmap-vscode>.
Glad that you like it.

**Comment by Tchoupinax** [comment]
Oh, thank you for your reactivity ! :100: 
It is installed ! :+1:
