### ISSUE TITLE
Support for markdown frontmatter

### ISSUE THREAD

**Issue by martintang** [gera2ld/markmap-vscode#20]
FrontMatter always used in markdown file for recording some infos, such as:
```
---
title: xxx
date: xxxx
tags: ["xxx", "xxx"]
---
```

and some other extensions can also use this FrontMatter's infos, such as "Nested tags".

Hope this wonderful extension can skip FrontMatter, or it will show wrong mindmap.
Thanks.

**Comment by flatrick** [comment]
I want to use this together with Dendron, but Dendron becomes really unhappy if a .md file is missing the Front Matter, and the Front Matter currently ruins the outputted mind map 😢
In other words, a bit of a Catch-22 situation..

**Comment by matthewbellringer** [comment]
Came here to request this for integration with Dendron too!
