### ISSUE TITLE
Suggestions: It would be helpful to have multiple roots.

### ISSUE THREAD

**Issue by xiehuihui** [gera2ld/markmap-vscode#24]
The rendering of Markmap always start from a single root. Multiple roots are not supported. 

![multiroots](https://user-images.githubusercontent.com/13328766/134278845-6ec43d14-b556-4b13-bca1-246ca62453c3.png)

**Comment by gera2ld** [comment]
It has nothing to do with your comment. It was by design to always have a root node.
