### ISSUE TITLE
Can I change color theme like what the webpage does?

### ISSUE THREAD

**Issue by splendidField** [gera2ld/markmap-vscode#27]

**Comment by gera2ld** [comment]
Yes in v0.0.13.
You can change the default options in extension settings (<kbd>cmd</kbd>+<kbd>,</kbd>), find `markmap`, you'll see `Default Options`.

For example, use solid color: `{"color":"#2980b9"}`.
This can also be set at markmap level by adding the options to frontmatter:

```md
---
markmap:
  color: #2980b9
---
```

**Comment by splendidField** [comment]
It works. Thank you!
