### ISSUE TITLE
The formula shows the problem.

### ISSUE THREAD

**Issue by 15874330629** [gera2ld/markmap-vscode#34]
Don't understand the problem, can you help me to reassure

![image](https://user-images.githubusercontent.com/52911891/172406526-977943f4-3d57-4ab9-a0a2-9ee91c431330.png)

**Comment by gera2ld** [comment]
Katex/Prism plugins depend on CSS from jsdelivr.com which I believe is blocked by your ISP. So you may need a proxy to get this work.

To confirm if it's blocked, try access https://cdn.jsdelivr.net/npm/markmap-view
