### ISSUE TITLE
Error on vscode

### ISSUE THREAD

**Issue by adamatti** [gera2ld/markmap-vscode#40]
I started to face this issue:
```
Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

... even with simple docs like 

```
# Main

## node 1

- test
- test 2
```

Is there something I can try to fix/debug?
Thanks in advance!

**Comment by gera2ld** [comment]
We don't have a service worker in VSCode so this is definitely not something from the extension.
Can you provide a reproduction? I have no idea what the issue is.

**Comment by adamatti** [comment]
Sorry... I tried both create a new doc (the previous one provided) or open an existing one and ran the `Open as markmap`, then got this error message. 
I will remove other extensions and try again.

**Comment by adamatti** [comment]
It is working again, not sure what happen

**Comment by githubpsyche** [comment]
Heyy, I have this same issue. Would be cool if we could figure out why it's happening.
