### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by mayneyao** [gera2ld/markmap-vscode#5]
Unable to install 'gera2ld.markmap-vscode' extension because it is not compatible with the current version of VS Code (version 1.45.1).

supported versions?

**Comment by gera2ld** [comment]
Isn't the current version of VSCode 1.51?

**Comment by mayneyao** [comment]
> Isn't the current version of VSCode 1.51?

It works when I upgrade my VSCode,  Thanks!
